languageCode = "en-us"
title = "Hi Hugo, meet Jo"
baseURL = "http://example.org/"
buildDrafts = true

theme = "jo"
publishDir = "docs"

backgroundColor = "blue"

[Author]
  name = "Jo Vliegen"
  email = "<i>fname</i>.<i>lname</i>A T<i>gmail.com</i>"
 
# [blackfriday] hrefTargetBlank = "true"
